### PR TITLE
Adding a JavaScript plotting frontend

### PR DESCRIPTION
**Pull request by emichael**
WIP

This commit adds a very simple view to return JSON blobs with times, as well as some javascript that uses plotly.js to make plots. Just run the development server and go to `/plot/`

AFAICT, we need to solve the following before shipping this:

- [x] @require_login for plot view and json api view
      Depends on users being able to make accounts and login
- [x] Cache results on the javascript side  
      My idea for this is basically to create a day -> result list dict and then make efficient queries for the right ranges
- [x] Limit size of range for query and handle the limit on the javascript side
- [ ] Add way to display completion streaks and win streaks
      This might require a better way of limiting the users we display
- [ ] Handle log/linear option
- [ ] Fix the weird issue with my normalization function

Nice things to have:
- [ ] Fix xtics to only display days, never times

### CODE REVIEW

**Comment by mwillsey** [comment]
Looks good. Couple thoughts so far:

- re: caching, `select user_id, date, seconds from crossbot_minicrosswordtime` returns 240kb of data for all 10k entries. Only 44kb gzipped. I think we can just send every date range every time for now.
- re: streaks, can we just handle that client side?

**Comment by emichael** [comment]
Oh, really, that's all? Why is the db 2.5M then?

In that case, we can simplify even further and not have to go back to the backend every time the user changes the settings. If we got all the data at once, we could even add a range slider directly in plotly like this: https://plot.ly/javascript/time-series/#time-series-with-rangeslider

We can definitely handle streaks client side. The issue is how you control the options win streaks. What someone's win streak looks like depends on the people you're plotting (otherwise the plot looks more or less like y = x for Lucy and y = 0 for the rest of us). The nice thing about plotly is that it handles turning lines on and off (try clicking on the legend). But that doesn't change the data. Maybe there's some javascript hook we can use to get a callback whenever someone clicks on the legend?

**Comment by mwillsey** [comment]
This will close #19 when merged.

**Comment by emichael** [comment]
We still need to fix/add a few things, but this should be safe to merge now. It'll be cool to see it on the live site.

**Pull request merged**
