### PR TITLE
Crossbucks 1.0

### PR DESCRIPTION
**Pull request by emichael**
Adding basic crossbucks implementation.

Right now, it just gives users crossbucks when they add a time and deletes them when it takes that time away.

### CODE REVIEW

**Comment by mwillsey** [comment]
Definitely needs tests. Also are we not dealing with the "rewards change and then they remove something" problem?

**Comment by emichael** [comment]
As of this commit, that's not a problem. Deleting a time removes crossbucks, so the invariant user.crossbucks == CROSBUCKS_PER_TIME * user.num_times is maintained.

**Comment by mwillsey** [comment]
Not if CROSSBUCKS_PER_TIME changes? Am i missing something?

**Comment by emichael** [comment]
Sure, if you change `CROSBUCKS_PER_SOLVE`, you'd have to write a migration to correct for it. But also we shouldn't change that constant once we set it.

**Pull request merged**
